### ISSUE TITLE
Error when building SSR website with `storyblokApi.get(storyUrl, apiParams, { cache: "no-store" })` and `generateStaticParams`

### ISSUE THREAD

**Issue by mllustosa** [storyblok/storyblok-react#1133]
### Describe the issue you're facing

When I run `next build` to build a NextJs (14) website in combination with using `storyblokApi.get(storyUrl, apiParams, { cache: "no-store" })` to dynamically build the initial static pages via `generateStaticParams()` I am getting this error during build time:

```
TypeError: u.includes is not a function
    at /Users/user/Projects/project/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:604
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at e_ (/Users/user/Projects/project/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:141547)
    at eP (/Users/user/Projects/project/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142537)
    at eE (/Users/user/Projects/project/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142698)
    at Timeout._onTimeout (/Users/user/Projects/project/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135475)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

When I stop using the storyblokApi and just fetch the stories directly via `fetch(storyUrlWithTokenAndParams, { cache: "no-store" })` the build works normally again.

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-vdxq2g?file=app%2F%5Blocale%5D%2F%5B%5B...slug%5D%5D%2Fpage.tsx

### Steps to reproduce

Ensure your .env `STORYBLOK_TOKEN` is set to a valid token.

### Steps
```
$ npm install
$ npm run build
```

### Expectation
A page would be built for each story with the content "I exist"

### Reality
The build fails with `TypeError: u.includes is not a function`.

### Remarks
If we don't use storyblokApi.get and instead just do a fetch to get the stories (with the proper params set as querystring and with cache set to "no-store") the build works fine.

### System Info

```shell
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M1 Pro
  Memory: 95.52 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
  npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
  bun: 1.1.3 - ~/.bun/bin/bun
  Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
Browsers:
  Chrome: 126.0.6478.63
  Safari: 17.5
Packages:
  react: 18.3.1
  react-dom: 18.3.1
  @storyblok/react: 3.0.10
```

### Used Package Manager

npm

### Error logs (Optional)

```
TypeError: u.includes is not a function
    at /Users/user/Projects/project/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:604
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at e_ (/Users/user/Projects/project/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:141547)
    at eP (/Users/user/Projects/project/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142537)
    at eE (/Users/user/Projects/project/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142698)
    at Timeout._onTimeout (/Users/user/Projects/project/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135475)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  digest: '528506355'
```

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by mllustosa** [comment]
Here is a [video](https://www.loom.com/share/a924f9b395794eacb3886bbdb933735c) showing the problem happening. I hope that helps debugging.

**Comment by sdechi** [comment]
I have the same error here. Its disappering as soon as I change from 
storyblokApi.get(url, params, {cache: "no-store"}); to storyblokApi.get(url, params);

**Comment by guanacone** [comment]
Same error here. If I remove `{cache: "no-store"}` from storyblok.get the live editing breaks.

**Comment by dipankarmaikap** [comment]
@mllustosa I tested your StackBlitz code with a Storyblok demo space preview access token, and the build completed without any issues. Could you please provide us with a minimal codebase where this error occurs or let us know the steps to reproduce it?

Thank you.

**Comment by guanacone** [comment]
@mllustosa build is not failing anymore. Maybe this was vercel issue.

**Comment by dipankarmaikap** [comment]
We are closing this issue due to inactivity. If you have new input or further information, please feel free to reopen it.

**Comment by lemsdentsu** [comment]
I'm also experiencing this issue, haven't found a solution yet. Anyone else any luck?

**Comment by edanlef** [comment]
We are also running into this exact issue on the latest version of @storyblok/react (3.0.15) and next (14.2.15)

**Comment by baptadn** [comment]
Same issue with 

```tsx
import { getStoryblokApi, StoryblokStory } from "@storyblok/react/rsc";
import { draftMode } from "next/headers";

export default async function Home() {
  const { isEnabled } = draftMode();
  const storyblokApi = getStoryblokApi();

  const { data } = await storyblokApi.get(
    `cdn/stories/home`,
    {
      version: isEnabled ? "draft" : "published",
    },
    { cache: "no-store" }
  );

  return <StoryblokStory story={data.story} />;
}
```

if I remove `{ cache: "no-store" }` it builds

**Comment by nilsgehlin** [comment]
We are also having this issue on next 14.2.15 and @storyblok/react 3.0.15

**Comment by WillHHH** [comment]
I'm still getting this issue on @storyblok/react 4.0.0
